server:
   servlet:
      context-path: /workshop
   port: 8080 
spring:
   flyway:
      locations: classpath:db/migrations
      defaultSchema: bet_schema
   datasource:
      url: jdbc:postgresql://localhost:5432/workshop
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
   jpa:
      hibernate:
         ddl-auto: none
      show-sql: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            '[format_sql]': true
            '[default_schema]': bet_schema
            
 