name: Java CI+CD
run-name: ${{ github.actor }} is starting the execution of backend pipeline "Java CI+CD" with GitHub Actions
on: workflow_dispatch
jobs:
  deploy:
    name: 'Backend CD'
    runs-on: self-hosted
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Update Kubernetes Configuration
        run: aws eks update-kubeconfig --region us-east-1 --name my_eks
