name: Java CI
run-name: ${{ github.actor }} is starting the execution of backend pipeline with GitHub Actions
on: workflow_dispatch
env:
  AWS_REGION: us-east-1 # set this to your preferred AWS region, e.g. us-west-1
jobs:
  build:
    name: 'Backend CI'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
          cache: maven
      - name: Build and Test with Maven
        run: mvn --batch-mode --update-snapshots verify sonar:sonar -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
